### ISSUE TITLE
SteemNodeRPC should throw an exception rather than retry

### ISSUE THREAD

**Issue by l0k18** [xeroc/piston-lib#35]
This function instead just keeps retrying the connection, which means it is not possible to set up fallback steemd rpc address, to enable this to be regulated by the calling script it should throw an exception, which could then try backups instead, or specify the retry timeout.

**Comment by xeroc** [comment]
you can use an array/list for `urls` instead of a single host. It will cycle through them automatically.
Also there is a `num_retries` parameter that, if set to 1, will make the call raise an exception if not connecting.

I realize it's not nicely documented as its a feature inherited from python-graphene: https://github.com/xeroc/python-graphenelib/blob/master/grapheneapi/graphenewsrpc.py#L21
